console.log("Hello! I'm your coding fun fact guide!");
let botName = "CodeBot3000";
let botLocation = "Silicon Valley";
let favoriteLanguage = "JavaScript";
console.log("My name is " + botName + " and I live on " + botLocation + ".");
console.log("My favorite programming language is " + favoriteLanguage + ".");
let codingFact = favoriteLanguage + " was created in just 10 days!";
console.log(codingFact);
codingFact = favoriteLanguage + " is one of the most widely used languages on the web.";
console.log(codingFact);
codingFact = favoriteLanguage + " can be used for frontend, backend, games, and even machine learning!";
console.log(codingFact);
console.log("It was fun sharing these facts with you. Goodbye! - " + botName + " from " + botLocation + ".");
